
[[dependencies]]
  branch = "master"
  name = "github.com/SparkPost/gosparkpost"

[[dependencies]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[dependencies]]
  branch = "master"
  name = "github.com/garyburd/go-oauth"

[[dependencies]]
  branch = "master"
  name = "github.com/go-fsnotify/fsnotify"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/securecookie"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/websocket"

[[dependencies]]
  branch = "master"
  name = "github.com/kjk/dailyrotate"

[[dependencies]]
  branch = "master"
  name = "github.com/kjk/siser"

[[dependencies]]
  branch = "master"
  name = "github.com/kr/fs"

[[dependencies]]
  branch = "master"
  name = "github.com/kurin/blazer"

[[dependencies]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[dependencies]]
  branch = "master"
  name = "github.com/russross/blackfriday"

[[dependencies]]
  branch = "master"
  name = "github.com/thomas11/atomgenerator"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"
